name: ff
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <4.0.0'

publish_to: none

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.4.1
  chalk: ^1.2.1
  interact: ^2.2.0
  path: ^1.8.3
  translator:
    git:
      url: https://github.com/gabrielpacheco23/google-translator.git
  yaml: ^3.1.2
  glob: ^2.1.2
  recase: ^4.1.0
  analyzer: ^6.4.1
  dart_style: ^2.3.6